import { Injectable } from '@angular/core';
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
import * as XLSX from 'xlsx';
import { ReglaSancion, Sancion } from './sancion.model';

(pdfMake as any).vfs = pdfFonts;

export interface SancionesExportables { ligaNombre: string; ligaImagen?: string; campeonatoNombre: string; tipoNombre: string; sanciones: Sancion[]; reglas: ReglaSancion[]; }

@Injectable({ providedIn: 'root' })
export class SancionesExportService {
  descargarPdf(data: SancionesExportables): void {
    const body = [['#', 'SANCIONADO', 'EQUIPO', 'SANCIÓN', 'CUMPLIMIENTO', 'ESTADO'].map(text => ({ text, style: 'tableHeader' })), ...data.sanciones.map((s, i) => [String(i + 1), this.persona(s), s.equipo?.nombre ?? '—', s.tipoSancion?.nombre ?? '—', this.cumplimiento(s), this.estado(s)])];
    pdfMake.createPdf({ pageMargins: [28, 32, 28, 32], pageOrientation: 'landscape', content: [{ text: 'REPORTE DE SANCIONES', style: 'title', alignment: 'center' }, { text: data.ligaNombre, style: 'league', alignment: 'center' }, { text: `${data.campeonatoNombre} · ${data.tipoNombre}`, style: 'subtitle', alignment: 'center', margin: [0, 3, 0, 14] }, { table: { headerRows: 1, widths: [24, '*', '*', '*', 90, 90], body }, layout: { fillColor: (row: number) => row === 0 ? '#243B5A' : row % 2 === 0 ? '#F5F7FA' : null } }, { text: `Generado el ${this.fecha()} · ${data.sanciones.length} sanción(es)`, style: 'footer', margin: [0, 14, 0, 0] }], styles: { title: { fontSize: 17, bold: true, color: '#1A252F' }, league: { fontSize: 11, bold: true, color: '#3498DB' }, subtitle: { fontSize: 10, color: '#52616B' }, footer: { fontSize: 8, color: '#7F8C8D' }, tableHeader: { bold: true, color: '#FFFFFF', fontSize: 8 } }, defaultStyle: { fontSize: 8 } } as any).download(`${this.nombre(data)}.pdf`);
  }
  descargarExcel(data: SancionesExportables): void {
    const hoja = XLSX.utils.aoa_to_sheet([['REPORTE DE SANCIONES'], ['Liga', data.ligaNombre], ['Campeonato', data.campeonatoNombre], ['Tipo', data.tipoNombre], ['Generado el', this.fecha()], [], ['N.º', 'Sancionado', 'Equipo', 'Tipo', 'Descripción', 'Cumplidos', 'Suspensión', 'Estado', 'Fecha'], ...data.sanciones.map((s, i) => [i + 1, this.persona(s), s.equipo?.nombre ?? '', s.tipoSancion?.nombre ?? '', s.descripcion ?? '', s.partidosCumplidos ?? 0, s.partidosSuspension ?? 0, this.estado(s), s.fechaSancion ?? ''])]);
    hoja['!cols'] = [{ wch: 7 }, { wch: 30 }, { wch: 25 }, { wch: 25 }, { wch: 42 }, { wch: 12 }, { wch: 13 }, { wch: 22 }, { wch: 15 }]; hoja['!merges'] = [XLSX.utils.decode_range('A1:I1')];
    const libro = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(libro, hoja, 'Sanciones'); XLSX.writeFile(libro, `${this.nombre(data)}.xlsx`);
  }
  async descargarImagen(data: SancionesExportables): Promise<void> {
    const logo = data.ligaImagen ? await this.urlADataUrl(data.ligaImagen) : undefined;
    const activas = data.sanciones
      .filter(s => s.activo && (s.suspensionActiva || ['equipo', 'barra', 'directivo'].includes(s.tipoSancion?.aplicaA ?? '')))
      .sort((a, b) => Number(!b.jugador) - Number(!a.jugador));
    const url = URL.createObjectURL(new Blob([this.svg(data, logo, activas.slice(0, 36))], { type: 'image/svg+xml;charset=utf-8' }));
    try { const imagen = await new Promise<HTMLImageElement>((resolve, reject) => { const el = new Image(); el.onload = () => resolve(el); el.onerror = () => reject(); el.src = url; }); const canvas = document.createElement('canvas'); canvas.width = 1080; canvas.height = 1920; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error(); ctx.drawImage(imagen, 0, 0); const png = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png')); if (!png) throw new Error(); const enlace = document.createElement('a'); enlace.href = URL.createObjectURL(png); enlace.download = `${this.nombre(data)}_ACTIVAS.png`; enlace.click(); URL.revokeObjectURL(enlace.href); } finally { URL.revokeObjectURL(url); }
  }
  private svg(data: SancionesExportables, logo: string | undefined, filas: Sancion[]): string {
    const inicio = 510, alto = 35;
    return this.svgLista(data, logo, filas);
    const items = filas.map((s, i) => { const y = inicio + i * alto; return `<rect x="54" y="${y}" width="972" height="${alto}" fill="${i % 2 ? '#fff' : '#F7F9FC'}"/><rect x="54" y="${y}" width="8" height="${alto}" fill="#E67E22"/><text x="88" y="${y + alto / 2 + 7}" class="num">${i + 1}</text><text x="130" y="${y + alto / 2 - 4}" class="name">${this.xml(this.cortar(this.persona(s), 35))}</text><text x="130" y="${y + alto / 2 + 20}" class="team">${this.xml(this.cortar(s.equipo?.nombre ?? 'Sin equipo', 35))}</text><text x="720" y="${y + alto / 2 + 7}" class="type">${this.xml(this.cortar(s.tipoSancion?.nombre ?? 'Sanción', 22))}</text><text x="974" y="${y + alto / 2 + 7}" class="count" text-anchor="end">${this.xml(this.cumplimiento(s))}</text>`; }).join('');
    const logoSvg = logo ? `<circle cx="948" cy="126" r="66" fill="#fff" opacity=".16"/><image href="${logo}" x="898" y="76" width="100" height="100" preserveAspectRatio="xMidYMid meet"/>` : '';
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#152238"/><stop offset="1" stop-color="#304C70"/></linearGradient></defs><style>.title{font:700 45px Arial;fill:#fff}.league{font:700 24px Arial;fill:#75D1FF}.meta{font:400 21px Arial;fill:#D9E5F2}.th{font:700 16px Arial;fill:#5C6B7A}.num{font:700 20px Arial;fill:#E67E22}.name{font:700 22px Arial;fill:#1A252F}.team{font:400 17px Arial;fill:#52616B}.type{font:600 18px Arial;fill:#34495E}.count{font:700 19px Arial;fill:#152238}.foot{font:400 16px Arial;fill:#6B7A8C}</style><rect width="1080" height="1350" fill="#EAF0F6"/><rect width="1080" height="258" fill="url(#bg)"/><text x="54" y="76" class="league">${this.xml(data.ligaNombre)}</text><text x="54" y="136" class="title">SANCIONES ACTIVAS</text><text x="54" y="183" class="meta">${this.xml(data.campeonatoNombre)} · ${this.xml(data.tipoNombre)}</text><text x="54" y="218" class="meta">Actualizado: ${this.fecha()}</text>${logoSvg}<rect x="54" y="276" width="972" height="996" rx="18" fill="#fff"/><rect x="54" y="276" width="972" height="52" fill="#EDF2F7"/><text x="88" y="309" class="th">#</text><text x="130" y="309" class="th">SANCIONADO / EQUIPO</text><text x="720" y="309" class="th">SANCIÓN</text><text x="974" y="309" class="th" text-anchor="end">CUMPLIMIENTO</text>${items}<text x="54" y="1304" class="foot">${filas.length} sanción(es) activas mostradas · Máximo 12</text><text x="1026" y="1304" class="foot" text-anchor="end">Sistema de Ligas Barriales</text></svg>`;
  }
  private svgLista(data: SancionesExportables, logo: string | undefined, filas: Sancion[]): string {
    const rows = filas.map((s, i) => { const y = 510 + i * 35, equipo = !s.jugador, texto = equipo ? this.avanceEquipo(s, data) : this.partidosPendientes(s); return `<text x="70" y="${y}" class="r">${equipo ? '' : this.xml(this.cortar(this.persona(s), 24))}</text><text x="380" y="${y}" class="r">${this.xml(this.cortar(s.equipo?.nombre ?? '', 22))}</text><text x="700" y="${y}" class="r" text-anchor="middle">${equipo ? '' : (s.numeroCanchaCalificacion ?? '')}</text><text x="1010" y="${y}" class="r b" text-anchor="end">${this.xml(this.cortar(texto, 24))}</text>`; }).join('');
    const watermark = logo ? `<image href="${logo}" x="270" y="800" width="540" height="540" opacity=".10"/>` : '', pie = logo ? `<image href="${logo}" x="930" y="1810" width="80" height="80"/>` : '';
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#02102f"/><stop offset=".55" stop-color="#06447f"/><stop offset="1" stop-color="#02102f"/></linearGradient></defs><style>.a{font:700 42px Arial;fill:#75a6d5}.b{font:700 50px Arial;fill:#cda412}.m{font:700 20px Arial;fill:white}.h{font:700 18px Arial;fill:white}.r{font:500 18px Arial;fill:white}.foot{font:700 14px Arial;fill:white}</style><rect width="1080" height="1920" fill="url(#g)"/><text x="55" y="150" class="a">JUGADORES Y EQUIPOS</text><text x="55" y="215" class="b">SANCIONADOS</text><text x="55" y="285" class="m">${this.xml(data.campeonatoNombre)} · ${this.fecha()}</text><path d="M45 405H1035L1005 440H75Z" fill="#cda412"/><text x="70" y="430" class="h">NOMBRE</text><text x="380" y="430" class="h">CLUB</text><text x="700" y="430" class="h" text-anchor="middle">NÚMERO</text><text x="1010" y="430" class="h" text-anchor="end">SANCIÓN</text>${watermark}${rows}<text x="55" y="1860" class="foot">COMISION TECNICA LMLT 2026-2028</text>${pie}</svg>`;
  }
  private persona(s: Sancion): string { return s.jugador?.nombre ?? s.equipo?.nombre ?? 'Sanción general'; }
  private cumplimiento(s: Sancion): string { return s.partidosSuspension > 0 ? `${s.partidosCumplidos ?? 0}/${s.partidosSuspension}` : s.fechaFinSuspension ? 'Por fecha' : 'Activa'; }
  private partidosPendientes(s: Sancion): string { const pendientes = Math.max(0, (s.partidosSuspension ?? 0) - (s.partidosCumplidos ?? 0)); return `${pendientes} PARTIDO${pendientes === 1 ? '' : 'S'}`; }
  private avanceEquipo(s: Sancion, data: SancionesExportables): string { const regla = data.reglas.find(r => r.tipoSancionId === s.tipoSancionId && r.acumulacionActiva && r.acumulacionCantidad); const total = data.sanciones.filter(x => x.equipoId === s.equipoId && x.tipoSancionId === s.tipoSancionId && x.activo).length; return regla ? `${s.tipoSancion?.nombre ?? 'SANCIÓN'}: ${total}/${regla.acumulacionCantidad}` : (s.descripcion?.trim() || s.tipoSancion?.nombre || 'SANCIÓN'); }
  private estado(s: Sancion): string { return !s.activo ? 'Anulada' : s.suspensionActiva ? 'Suspensión activa' : 'Sin suspensión activa'; }
  private fecha(): string { return new Intl.DateTimeFormat('es-EC', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date()); }
  private cortar(valor: string, limite: number): string { return valor.length > limite ? `${valor.slice(0, limite - 1)}…` : valor; }
  private xml(valor: string): string { return valor.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c] || c)); }
  private nombre(data: SancionesExportables): string { return `SANCIONES_${data.campeonatoNombre}`.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_|_$/g, '').toUpperCase(); }
  private async urlADataUrl(url: string): Promise<string | undefined> { if (url.startsWith('data:')) return url; try { const respuesta = await fetch(url); if (!respuesta.ok) return undefined; const blob = await respuesta.blob(); return await new Promise<string>((resolve, reject) => { const lector = new FileReader(); lector.onload = () => resolve(lector.result as string); lector.onerror = () => reject(); lector.readAsDataURL(blob); }); } catch { return undefined; } }
}
