import { Injectable } from '@angular/core'; import pdfMake from 'pdfmake/build/pdfmake'; import pdfFonts from 'pdfmake/build/vfs_fonts'; import * as XLSX from 'xlsx'; import { Partido } from './partido.model';
(pdfMake as any).vfs = pdfFonts;
export interface PartidosExport { liga: string; ligaImagen?: string; campeonato: string; categoria: string; etapa: string; jornada?: number | null; partidos: Partido[]; }
@Injectable({ providedIn: 'root' }) export class PartidosExportService {
  pdf(d: PartidosExport) { const rows = [['Jornada', 'Local', 'Resultado', 'Visitante', 'Estado'].map(t => ({ text: t, style: 'h' })), ...d.partidos.map(p => [String(p.jornada), p.equipoLocal?.nombre ?? '', p.estado === 'jugado' ? `${p.golesLocal} - ${p.golesVisitante}` : 'VS', p.equipoVisitante?.nombre ?? '', p.estado])]; pdfMake.createPdf({ content: [{ text: 'RESULTADOS Y PARTIDOS', style: 't', alignment: 'center' }, { text: `${d.liga} · ${d.campeonato} · ${d.categoria} · ${d.etapa}`, alignment: 'center', margin: [0, 4, 0, 14] }, { table: { headerRows: 1, widths: [55, '*', 65, '*', 75], body: rows } }], styles: { t: { bold: true, fontSize: 17 }, h: { bold: true, color: '#fff', fillColor: '#243B5A' } } } as any).download(this.nombre(d) + '.pdf'); }
  excel(d: PartidosExport) { const h = XLSX.utils.aoa_to_sheet([['RESULTADOS Y PARTIDOS'], ['Liga', d.liga], ['Campeonato', d.campeonato], ['Categoría', d.categoria], ['Etapa', d.etapa], ['Jornada', d.jornada ?? 'Todas'], [], ['Jornada', 'Local', 'Goles local', 'Goles visitante', 'Visitante', 'Estado', 'Fecha', 'Hora'], ...d.partidos.map(p => [p.jornada, p.equipoLocal?.nombre ?? '', p.golesLocal ?? '', p.golesVisitante ?? '', p.equipoVisitante?.nombre ?? '', p.estado, p.fechaPartido ?? '', p.horaPartido ?? ''])]); h['!cols'] = Array(8).fill({ wch: 20 }); const b = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(b, h, 'Partidos'); XLSX.writeFile(b, this.nombre(d) + '.xlsx'); }
  async imagen(d: PartidosExport) { const logo = d.ligaImagen ? await this.dataUrl(d.ligaImagen) : undefined, url = URL.createObjectURL(new Blob([this.svg(d, logo)], { type: 'image/svg+xml' })); try { const i = await new Promise<HTMLImageElement>((ok, no) => { const x = new Image(); x.onload = () => ok(x); x.onerror = no; x.src = url; }); const c = document.createElement('canvas'); c.width = 1080; c.height = 1350; c.getContext('2d')!.drawImage(i, 0, 0); const b = await new Promise<Blob | null>(ok => c.toBlob(ok, 'image/png')); if (!b) throw new Error(); const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = this.nombre(d) + '_JORNADA.png'; a.click(); URL.revokeObjectURL(a.href); } finally { URL.revokeObjectURL(url); } }
  private svg(d: PartidosExport, logo?: string) { const ps = d.partidos.slice(0, 18), rows = ps.map((p, i) => { const y = 330 + i * 52, m = p.estado === 'jugado' ? `${p.golesLocal}  -  ${p.golesVisitante}` : 'VS'; return `<rect x="78" y="${y}" width="405" height="36" fill="#F1F5F9"/><rect x="483" y="${y}" width="114" height="36" fill="#111827"/><rect x="597" y="${y}" width="405" height="36" fill="#F1F5F9"/><text x="465" y="${y+24}" class="team" text-anchor="end">${this.x(p.equipoLocal?.nombre ?? '')}</text><text x="540" y="${y+24}" class="score" text-anchor="middle">${m}</text><text x="615" y="${y+24}" class="team">${this.x(p.equipoVisitante?.nombre ?? '')}</text>`; }).join(''), logoHead = logo ? `<image href="${logo}" x="900" y="45" width="125" height="125" preserveAspectRatio="xMidYMid meet"/>` : '', watermark = logo ? `<image href="${logo}" x="300" y="610" width="480" height="480" opacity=".10" preserveAspectRatio="xMidYMid meet"/>` : ''; return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350"><style>.title{font:700 44px Arial;fill:#fff}.meta{font:600 22px Arial;fill:#dbeafe}.team{font:700 18px Arial;fill:#111827}.score{font:700 19px Arial;fill:#f59e0b}</style><rect width="1080" height="1350" fill="#063b75"/><rect width="1080" height="260" fill="#183554"/><text x="54" y="75" class="meta">${this.x(d.liga)}</text><text x="54" y="140" class="title">RESULTADOS - JORNADA ${d.jornada}</text><text x="54" y="190" class="meta">${this.x(d.campeonato)} · ${this.x(d.categoria)}</text><text x="54" y="225" class="meta">${this.x(d.etapa)} · Actualizado: ${new Intl.DateTimeFormat('es-EC').format(new Date())}</text>${logoHead}${watermark}${rows}<text x="54" y="1285" style="font:16px Arial;fill:#dbeafe">Sistema de Ligas Barriales</text></svg>`; }
  private nombre(d: PartidosExport) { return `PARTIDOS_${d.campeonato}_J${d.jornada ?? 'TODAS'}`.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '_').toUpperCase(); } private x(v: string) { return v.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]!)); } private async dataUrl(url: string): Promise<string | undefined> { if (url.startsWith('data:')) return url; try { const r = await fetch(url); if (!r.ok) return undefined; const b = await r.blob(); return await new Promise<string>((ok, no) => { const f = new FileReader(); f.onload = () => ok(f.result as string); f.onerror = no; f.readAsDataURL(b); }); } catch { return undefined; } }
}
